# -*- coding: utf-8 -*-
"""Steel_plate_code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n1GpCozpsEIqlCwTyRKIag152tAIc0zs
"""

import pandas as pd

Data_Fault = pd.read_csv('Steel Plates Faults Data Set.csv')

Data_Fault